name: Preflight
description: Does the preflight check
inputs:
  platforms:
    description: The platforms for which the image will be built
    default: linux/amd64,linux/arm64
    required: true
  images:
    description: Base names of the image tags
    required: false
  report-name:
    description: The name of the output report
    required: true
  redhat-project-id:
    description: The id for the redhat project.
    required: true
  pyxis-api-token:
    description: The pyxis api token
    required: true
  should-submit:
    description: Whether to submit the results to Red Hat
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
  - name: Build image metadata
    uses: ./.github/actions/metadata
    id: meta
    with:
      platforms: ${{ inputs.platforms }}
      images: ${{ inputs.images }}
  - name: Run preflight on image
    shell: bash
    env:
      RHCC_APITOKEN: ${{ inputs.pyxis-api-token }}
      RHCC_PROJECT_ID: ${{ inputs.redhat-project-id }}
      # renovate datasource=github-releases depName=redhat-openshift-ecosystem/openshift-preflight
      PREFLIGHT_VERSION: 1.15.2
    run: |
      hack/build/ci/preflight.sh "${{ env.PREFLIGHT_VERSION }}" "${{ steps.meta.outputs.tags }}" "${{ inputs.report-name }}" "${{ inputs.should-submit }}"
#  - name: Upload report
#    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
#    with:
#      name: preflight-report
#      path: ${{ inputs.report-name }}
