name: CI

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - "*"
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  build-push:
    name: Build images
    environment: Release
    runs-on: ubuntu-24.04
    env:
      GCR_IMAGE: gcr.io/${{ vars.GCR_REPOSITORY }}
      ECR_IMAGE: public.ecr.aws/${{ vars.ECR_REPOSITORY }}
      RHCC_IMAGE: quay.io/${{ vars.RHCC_REPOSITORY }}
      DOCKER_IMAGE: docker.io/${{ vars.DOCKERHUB_REPOSITORY }}
    steps:
      - name: first
        run: |
          echo "images: ${{ env.RHCC_IMAGE }},${{ env.GCR_IMAGE }},${{ env.ECR_IMAGE }},${{ env.DOCKER_IMAGE }}"
